In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('bs140513_032310.csv')

In [3]:
df.head()

step       customer  age gender zipcodeOri       merchant zipMerchant  \
0     0  'C1093826151'  '4'    'M'    '28007'   'M348934600'     '28007'   
1     0   'C352968107'  '2'    'M'    '28007'   'M348934600'     '28007'   
2     0  'C2054744914'  '4'    'F'    '28007'  'M1823072687'     '28007'   
3     0  'C1760612790'  '3'    'M'    '28007'   'M348934600'     '28007'   
4     0   'C757503768'  '5'    'M'    '28007'   'M348934600'     '28007'   

              category  amount  fraud  
0  'es_transportation'    4.55      0  
1  'es_transportation'   39.68      0  
2  'es_transportation'   26.89      0  
3  'es_transportation'   17.25      0  
4  'es_transportation'   35.72      0

In [4]:
x = df.drop(['step', 'customer', 'zipcodeOri', 'zipMerchant'], axis = 1)

In [5]:
x

age gender       merchant             category  amount  fraud
0       '4'    'M'   'M348934600'  'es_transportation'    4.55      0
1       '2'    'M'   'M348934600'  'es_transportation'   39.68      0
2       '4'    'F'  'M1823072687'  'es_transportation'   26.89      0
3       '3'    'M'   'M348934600'  'es_transportation'   17.25      0
4       '5'    'M'   'M348934600'  'es_transportation'   35.72      0
...     ...    ...            ...                  ...     ...    ...
594638  '3'    'F'  'M1823072687'  'es_transportation'   20.53      0
594639  '4'    'F'  'M1823072687'  'es_transportation'   50.73      0
594640  '2'    'F'   'M349281107'         'es_fashion'   22.44      0
594641  '5'    'M'  'M1823072687'  'es_transportation'   14.46      0
594642  '4'    'F'  'M1823072687'  'es_transportation'   26.93      0

[594643 rows x 6 columns]

In [6]:
variable1 = x.age.astype('category').cat.codes

In [7]:
variable1.unique()

array([4, 2, 3, 5, 1, 6, 7, 0], dtype=int8)

In [8]:
x.age.unique()

array(["'4'", "'2'", "'3'", "'5'", "'1'", "'6'", "'U'", "'0'"],
      dtype=object)

In [9]:
x.gender.unique()

array(["'M'", "'F'", "'E'", "'U'"], dtype=object)

In [10]:
x.gender.astype('category').cat.codes.unique()

array([2, 1, 0, 3], dtype=int8)

In [11]:
x.gender.value_counts()

'F'    324565
'M'    268385
'E'      1178
'U'       515
Name: gender, dtype: int64

In [12]:
var = ["'M'", "'F'", "'E'", "'U'"]

In [13]:
m = {'M':1, 'F':2, 'E':3, 'U':4}

In [14]:
x['age'].unique()

array(["'4'", "'2'", "'3'", "'5'", "'1'", "'6'", "'U'", "'0'"],
      dtype=object)

In [15]:
x['age'].astype('category').cat.codes.unique()

array([4, 2, 3, 5, 1, 6, 7, 0], dtype=int8)

In [16]:
columns = ['46-55','26-35','36-45','56-65','19-25','Above 65', 'Unknown', '0-18']

In [17]:
age = pd.DataFrame(data = [4, 2, 3, 5, 1, 6, 7, 0])

In [18]:
age['category'] = columns

In [19]:
age

0  category
0  4     46-55
1  2     26-35
2  3     36-45
3  5     56-65
4  1     19-25
5  6  Above 65
6  7   Unknown
7  0      0-18

In [21]:
age = pd.DataFrame({'46-55':[4],
                   '26-35':[2],
                   '36-45':[3],
                   '56-65':[5],
                   '19-25':[1],
                   'Above 65':[6],
                   'Unknown':[7],
                   '0-18':[0]})

In [22]:
age

46-55  26-35  36-45  56-65  19-25  Above 65  Unknown  0-18
0      4      2      3      5      1         6        7     0

In [23]:
age['36-45'][0]

3

In [24]:
ls = [age['36-45'][0]]

In [25]:
ls = [ls]

In [26]:
ls

[[3]]

In [27]:
age['46-55'][0]

4

In [28]:
age['46-55'][0]

4

In [29]:
age.columns

Index(['46-55', '26-35', '36-45', '56-65', '19-25', 'Above 65', 'Unknown',
       '0-18'],
      dtype='object')

In [30]:
x['gender'].unique()

array(["'M'", "'F'", "'E'", "'U'"], dtype=object)

In [31]:
x['gender'].astype('category').cat.codes.unique()

array([2, 1, 0, 3], dtype=int8)

In [32]:
gender = pd.DataFrame({'Male':[2],
                      'Female':[1],
                      'Enterprise':[0],
                      'Unknown': [3]})

In [33]:
gender

Male  Female  Enterprise  Unknown
0     2       1           0        3

In [34]:
ls = [age['46-55'][0], gender['Male'][0]]

In [35]:
ls

[4, 2]

In [36]:
x['merchant'].unique()

array(["'M348934600'", "'M1823072687'", "'M50039827'", "'M1888755466'",
       "'M1053599405'", "'M85975013'", "'M480139044'", "'M692898500'",
       "'M348875670'", "'M151143676'", "'M840466850'", "'M1741626453'",
       "'M1535107174'", "'M855959430'", "'M349281107'", "'M209847108'",
       "'M2122776122'", "'M1873032707'", "'M2011752106'", "'M857378720'",
       "'M1198415165'", "'M1748431652'", "'M980657600'", "'M1352454843'",
       "'M117188757'", "'M547558035'", "'M17379832'", "'M1649169323'",
       "'M1946091778'", "'M97925176'", "'M923029380'", "'M1353266412'",
       "'M1842530320'", "'M677738360'", "'M1313686961'", "'M732195782'",
       "'M1600850729'", "'M1872033263'", "'M3697346'", "'M495352832'",
       "'M1400236507'", "'M1294758098'", "'M1913465890'", "'M45060432'",
       "'M78078399'", "'M2080407379'", "'M1788569036'", "'M1416436880'",
       "'M933210764'", "'M1726401631'"], dtype=object)

In [37]:
merchant = pd.DataFrame()

In [38]:
merchant['Merch'] = ['M348934600', 'M1823072687', 'M50039827', 'M1888755466',
       'M1053599405', 'M85975013', 'M480139044', 'M692898500',
       'M348875670', 'M151143676', 'M840466850', 'M1741626453',
       'M1535107174', 'M855959430', 'M349281107', 'M209847108',
       'M2122776122', 'M1873032707', 'M2011752106', 'M857378720',
       'M1198415165', 'M1748431652', 'M980657600', 'M1352454843',
       'M117188757', 'M547558035', 'M17379832', 'M1649169323',
       'M1946091778', 'M97925176', 'M923029380', 'M1353266412',
       'M1842530320', 'M677738360', 'M1313686961', 'M732195782',
       'M1600850729', 'M1872033263', 'M3697346', 'M495352832',
       'M1400236507', 'M1294758098', 'M1913465890', 'M45060432',
       'M78078399', 'M2080407379', 'M1788569036', 'M1416436880',
       'M933210764', 'M1726401631']

In [39]:
x['merchant'].astype('category').cat.codes.unique()

array([30, 18, 36, 22,  0, 45, 34, 39, 29,  9, 42, 15, 10, 43, 31, 27, 28,
       21, 25, 44,  2, 16, 49,  5,  1, 37, 14, 12, 24, 48, 46,  6, 19, 38,
        4, 40, 11, 20, 32, 35,  7,  3, 23, 33, 41, 26, 17,  8, 47, 13],
      dtype=int8)

In [40]:
merchant['code'] = [30, 18, 36, 22,  0, 45, 34, 39, 29,  9, 42, 15, 10, 43, 31, 27, 28,
       21, 25, 44,  2, 16, 49,  5,  1, 37, 14, 12, 24, 48, 46,  6, 19, 38,
        4, 40, 11, 20, 32, 35,  7,  3, 23, 33, 41, 26, 17,  8, 47, 13]

In [41]:
merchant.iloc[:1]['code']

0    30
Name: code, dtype: int64

In [42]:
merchant = pd.Series(merchant['code'].values, index=merchant['Merch']).to_dict()

In [47]:
print(merchant)

{'M348934600': 30, 'M1823072687': 18, 'M50039827': 36, 'M1888755466': 22, 'M1053599405': 0, 'M85975013': 45, 'M480139044': 34, 'M692898500': 39, 'M348875670': 29, 'M151143676': 9, 'M840466850': 42, 'M1741626453': 15, 'M1535107174': 10, 'M855959430': 43, 'M349281107': 31, 'M209847108': 27, 'M2122776122': 28, 'M1873032707': 21, 'M2011752106': 25, 'M857378720': 44, 'M1198415165': 2, 'M1748431652': 16, 'M980657600': 49, 'M1352454843': 5, 'M117188757': 1, 'M547558035': 37, 'M17379832': 14, 'M1649169323': 12, 'M1946091778': 24, 'M97925176': 48, 'M923029380': 46, 'M1353266412': 6, 'M1842530320': 19, 'M677738360': 38, 'M1313686961': 4, 'M732195782': 40, 'M1600850729': 11, 'M1872033263': 20, 'M3697346': 32, 'M495352832': 35, 'M1400236507': 7, 'M1294758098': 3, 'M1913465890': 23, 'M45060432': 33, 'M78078399': 41, 'M2080407379': 26, 'M1788569036': 17, 'M1416436880': 8, 'M933210764': 47, 'M1726401631': 13}


In [235]:
merchant = pd.DataFrame(merchant,index=range(0,50))

In [236]:
merchant = merchant[:1]

In [237]:
merchant

M348934600  M1823072687  M50039827  M1888755466  M1053599405  M85975013  \
0          30           18         36           22            0         45   

   M480139044  M692898500  M348875670  M151143676  ...  M1400236507  \
0          34          39          29           9  ...            7   

   M1294758098  M1913465890  M45060432  M78078399  M2080407379  M1788569036  \
0            3           23         33         41           26           17   

   M1416436880  M933210764  M1726401631  
0            8          47           13  

[1 rows x 50 columns]

In [227]:
x['category'].unique()

array(["'es_transportation'", "'es_health'", "'es_otherservices'",
       "'es_food'", "'es_hotelservices'", "'es_barsandrestaurants'",
       "'es_tech'", "'es_sportsandtoys'", "'es_wellnessandbeauty'",
       "'es_hyper'", "'es_fashion'", "'es_home'", "'es_contents'",
       "'es_travel'", "'es_leisure'"], dtype=object)

In [238]:
x['category'].astype('category').cat.codes.unique()

array([12,  4,  9,  3,  6,  0, 11, 10, 14,  7,  2,  5,  1, 13,  8],
      dtype=int8)

In [239]:
category = pd.DataFrame()

In [240]:
category['cat'] = ['Transportation', 'Health', 'Other services',
       'Food', 'Hotel services', 'Bars and Restaurants',
       'Tech', 'Sport Sand Toys', 'Wellness and Beauty',
       'Hyper', 'Fashion', 'Home', 'Contents',
       'Travel', 'Leisure']

In [241]:
category['code'] = [12,  4,  9,  3,  6,  0, 11, 10, 14,  7,  2,  5,  1, 13,  8]

In [242]:
category

cat  code
0         Transportation    12
1                 Health     4
2         Other services     9
3                   Food     3
4         Hotel services     6
5   Bars and Restaurants     0
6                   Tech    11
7        Sport Sand Toys    10
8    Wellness and Beauty    14
9                  Hyper     7
10               Fashion     2
11                  Home     5
12              Contents     1
13                Travel    13
14               Leisure     8

In [243]:
category = pd.Series(category['code'].values, index=category['cat']).to_dict()

In [244]:
category

{'Transportation': 12,
 'Health': 4,
 'Other services': 9,
 'Food': 3,
 'Hotel services': 6,
 'Bars and Restaurants': 0,
 'Tech': 11,
 'Sport Sand Toys': 10,
 'Wellness and Beauty': 14,
 'Hyper': 7,
 'Fashion': 2,
 'Home': 5,
 'Contents': 1,
 'Travel': 13,
 'Leisure': 8}

In [246]:
category = pd.DataFrame(category,index=range(0,14))

In [250]:
category = category[:1]

In [251]:
merchant

M348934600  M1823072687  M50039827  M1888755466  M1053599405  M85975013  \
0          30           18         36           22            0         45   

   M480139044  M692898500  M348875670  M151143676  ...  M1400236507  \
0          34          39          29           9  ...            7   

   M1294758098  M1913465890  M45060432  M78078399  M2080407379  M1788569036  \
0            3           23         33         41           26           17   

   M1416436880  M933210764  M1726401631  
0            8          47           13  

[1 rows x 50 columns]

In [252]:
category.to_csv('category_codes.csv', index=False)
merchant.to_csv('merchant_codes.csv', index = False)
age.to_csv('age_codes.csv', index = False)
gender.to_csv('gender_codes.csv', index=False)